/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ebytgsuudvhsoedwhonv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVieXRnc3V1ZHZoc29lZHdob252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNjEzODEsImV4cCI6MjA5MTgzNzM4MX0.Up9p-UqyvQapxasGmRu_e-ZHRg96F0L3Fw_DBfsdHVI"